CREATE DATABASE BillingAppDB;
GO

USE BillingAppDB;
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'HS_BILL_CUSTOMERS')
BEGIN
    CREATE TABLE HS_BILL_CUSTOMERS (
        CUSTOMER_ID INT IDENTITY PRIMARY KEY,
        FIRST_NAME NVARCHAR(100) NOT NULL,
        LAST_NAME NVARCHAR(100) NOT NULL,
        EMAIL NVARCHAR(200) UNIQUE NOT NULL,
        PHONE NVARCHAR(20),
        ADDRESS NVARCHAR(500),
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        IS_ACTIVE BIT DEFAULT 1
    )
END